






# file: ibert_ultrascale_gty_0.xdc
####################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_ultrascale_gty_0.xdc
## /___/   / ## \   \  / ##  \___\/\___ ##
##
##
## Generated by Xilinx IBERT Ultrascale
##**************************************************************************
##
## Icon Constraints
##





create_clock -period 10.000 -name D_CLK [get_ports gty_sysclkp_i]
set_clock_groups -asynchronous -group [get_clocks D_CLK -include_generated_clocks]

##
##gtrefclk lock constraints
##







set_property PACKAGE_PIN Y10 [get_ports {gty_refclk0n_i[0]}]
set_property PACKAGE_PIN Y11 [get_ports {gty_refclk0p_i[0]}]
set_property PACKAGE_PIN V10 [get_ports {gty_refclk1n_i[0]}]
set_property PACKAGE_PIN V11 [get_ports {gty_refclk1p_i[0]}]


set_property PACKAGE_PIN D10 [get_ports {gty_refclk0n_i[1]}]
set_property PACKAGE_PIN D11 [get_ports {gty_refclk0p_i[1]}]
set_property PACKAGE_PIN B10 [get_ports {gty_refclk1n_i[1]}]
set_property PACKAGE_PIN B11 [get_ports {gty_refclk1p_i[1]}]
##
## Refclk constraints
##






create_clock -period 6.207 -name gtrefclk0_23 [get_ports {gty_refclk0p_i[0]}]
create_clock -period 6.207 -name gtrefclk1_23 [get_ports {gty_refclk1p_i[0]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_23 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_23 -include_generated_clocks]

create_clock -period 6.207 -name gtrefclk0_27 [get_ports {gty_refclk0p_i[1]}]
create_clock -period 6.207 -name gtrefclk1_27 [get_ports {gty_refclk1p_i[1]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_27 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_27 -include_generated_clocks]
##
## System clock pin locs and timing constraints
##
set_property PACKAGE_PIN AY23 [get_ports gty_sysclkp_i]
# NOTE: vendor export had LVDS here, which is wrong for this board and DRC-fails:
# AY23/BA23 are the 100 MHz board clock in bank 64, which is a 1.2V bank.
# vu13p/xdc/vu13p_clock.xdc constrains the same pins as DIFF_SSTL12.
# (BA23 needs no PACKAGE_PIN - Vivado infers the N pin of the L12 diff pair.)
set_property IOSTANDARD DIFF_SSTL12 [get_ports gty_sysclkp_i]

